---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: logging
spec:
    type: custom
    parameters:
        - name: telemetry_types
          value:
            - Metrics
            - Logs
            - Traces
        - name: configuration
          value: 'logging:'
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: Google
spec:
    type: googlecloud
    parameters:
        - name: project
          value: bpcli-dev
        - name: auth_type
          value: json
        - name: credentials
          value: (sensitive)
          sensitive: true
        - name: credentials_file
          value: ""
        - name: sending_queue_enabled
          value: true
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_directory
          value: $OIQ_OTEL_COLLECTOR_HOME/storage
        - name: enable_compression
          value: true
        - name: enable_wal
          value: false
        - name: wal_max_backoff
          value: 60
status:
    latest: true
---
apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    name: k8s-logs
    labels:
        platform: kubernetes-daemonset
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - type: k8s_container
          parameters:
            - name: cluster_name
              value: stage
            - name: log_source
              value: file
            - name: file_path
              value:
                - /var/log/containers/*.log
            - name: exclude_file_path
              value:
                - /var/log/containers/observiq-*-collector-*
                - /var/log/containers/bindplane-*-agent-*
            - name: journald_path
              value: ""
            - name: start_at
              value: end
          processors:
            - type: batch
              parameters:
                - name: send_batch_size
                  value: 8192
                - name: send_batch_max_size
                  value: 0
                - name: timeout
                  value: 200ms
    destinations:
        - name: logging
    selector:
        matchLabels:
            configuration: k8s-logs
---
apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    name: bindplane
    labels:
        platform: linux
spec:
    contentType: ""
    measurementInterval: ""
    sources:
        - type: otlp
          parameters:
            - name: listen_address
              value: 0.0.0.0
            - name: grpc_port
              value: 4317
            - name: http_port
              value: 4318
            - name: enable_tls
              value: false
            - name: cert_file
              value: ""
            - name: key_file
              value: ""
            - name: mutual_tls
              value: false
            - name: ca_file
              value: ""
            - name: enable_grpc_timeout
              value: true
            - name: grpc_max_connection_idle
              value: 60
            - name: grpc_max_connection_age
              value: 60
            - name: grpc_max_connection_age_grace
              value: 300
          processors:
            - type: batch
              parameters:
                - name: send_batch_size
                  value: 8192
                - name: send_batch_max_size
                  value: 0
                - name: timeout
                  value: 200ms
    destinations:
        - name: logging
    selector:
        matchLabels:
            configuration: bindplane
